CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    domain VARCHAR(190) NOT NULL,
    logo_url TEXT NULL,
    vapid_subject VARCHAR(255) NOT NULL,
    vapid_public_key TEXT NOT NULL,
    vapid_private_key TEXT NOT NULL,
    webhook_secret_hash CHAR(64) NOT NULL,
    smtp_profile VARCHAR(40) NULL,
    settings JSON NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY tenants_key_unique (`key`),
    UNIQUE KEY tenants_domain_unique (domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    endpoint_hash CHAR(64) NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth_token VARCHAR(255) NOT NULL,
    content_encoding VARCHAR(30) NOT NULL DEFAULT 'aes128gcm',
    filters JSON NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    failure_count INT UNSIGNED NOT NULL DEFAULT 0,
    user_agent TEXT NULL,
    browser VARCHAR(80) NULL,
    device VARCHAR(80) NULL,
    platform VARCHAR(80) NULL,
    ip_hash CHAR(64) NULL,
    last_seen_at DATETIME NULL,
    last_success_at DATETIME NULL,
    expired_at DATETIME NULL,
    unsubscribed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY push_public_id_unique (public_id),
    UNIQUE KEY push_tenant_endpoint_unique (tenant_id, endpoint_hash),
    KEY push_tenant_status_index (tenant_id, status),
    KEY push_last_seen_index (last_seen_at),
    CONSTRAINT push_tenant_foreign FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS email_subscriptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    email_hash CHAR(64) NOT NULL,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(160) NULL,
    filters JSON NULL,
    frequency VARCHAR(20) NOT NULL DEFAULT 'immediate',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    verification_token_hash CHAR(64) NULL,
    unsubscribe_token_hash CHAR(64) NOT NULL,
    verified_at DATETIME NULL,
    last_sent_at DATETIME NULL,
    last_active_at DATETIME NULL,
    unsubscribed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY email_public_id_unique (public_id),
    UNIQUE KEY email_tenant_address_unique (tenant_id, email_hash),
    KEY email_tenant_status_index (tenant_id, status),
    CONSTRAINT email_tenant_foreign FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    external_id VARCHAR(190) NULL,
    kind VARCHAR(30) NOT NULL DEFAULT 'manual',
    title VARCHAR(160) NOT NULL,
    body TEXT NOT NULL,
    target_url TEXT NOT NULL,
    icon_url TEXT NULL,
    image_url TEXT NULL,
    channels JSON NOT NULL,
    audience_filters JSON NULL,
    content JSON NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    scheduled_at DATETIME NULL,
    processing_started_at DATETIME NULL,
    completed_at DATETIME NULL,
    total_count INT UNSIGNED NOT NULL DEFAULT 0,
    sent_count INT UNSIGNED NOT NULL DEFAULT 0,
    failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    delivered_count INT UNSIGNED NOT NULL DEFAULT 0,
    opened_count INT UNSIGNED NOT NULL DEFAULT 0,
    clicked_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY campaigns_public_id_unique (public_id),
    UNIQUE KEY campaigns_tenant_external_unique (tenant_id, external_id),
    KEY campaigns_tenant_status_schedule_index (tenant_id, status, scheduled_at),
    CONSTRAINT campaigns_tenant_foreign FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deliveries (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    campaign_id BIGINT UNSIGNED NULL,
    channel VARCHAR(20) NOT NULL,
    push_subscription_id BIGINT UNSIGNED NULL,
    email_subscription_id BIGINT UNSIGNED NULL,
    recipient_hash CHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 4,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at DATETIME NULL,
    locked_by VARCHAR(100) NULL,
    provider_message_id VARCHAR(255) NULL,
    error_code VARCHAR(80) NULL,
    error_message TEXT NULL,
    payload JSON NOT NULL,
    sent_at DATETIME NULL,
    delivered_at DATETIME NULL,
    opened_at DATETIME NULL,
    clicked_at DATETIME NULL,
    failed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY deliveries_public_id_unique (public_id),
    UNIQUE KEY deliveries_campaign_push_unique (campaign_id, channel, push_subscription_id),
    UNIQUE KEY deliveries_campaign_email_unique (campaign_id, channel, email_subscription_id),
    KEY deliveries_queue_index (status, available_at, id),
    KEY deliveries_tenant_status_index (tenant_id, status),
    KEY deliveries_campaign_index (campaign_id),
    CONSTRAINT deliveries_tenant_foreign FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT deliveries_campaign_foreign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
    CONSTRAINT deliveries_push_foreign FOREIGN KEY (push_subscription_id) REFERENCES push_subscriptions(id) ON DELETE SET NULL,
    CONSTRAINT deliveries_email_foreign FOREIGN KEY (email_subscription_id) REFERENCES email_subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivery_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    delivery_id BIGINT UNSIGNED NOT NULL,
    event VARCHAR(30) NOT NULL,
    metadata JSON NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY delivery_events_delivery_index (delivery_id, occurred_at),
    CONSTRAINT delivery_events_delivery_foreign FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS email_digest_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    email_subscription_id BIGINT UNSIGNED NOT NULL,
    content_key VARCHAR(190) NOT NULL,
    content JSON NOT NULL,
    due_at DATETIME NOT NULL,
    claimed_at DATETIME NULL,
    delivery_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY digest_subscription_content_unique (email_subscription_id, content_key),
    KEY digest_due_index (due_at, claimed_at),
    CONSTRAINT digest_tenant_foreign FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT digest_email_foreign FOREIGN KEY (email_subscription_id) REFERENCES email_subscriptions(id) ON DELETE CASCADE,
    CONSTRAINT digest_delivery_foreign FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
